spring.application.name=guarderia-canina

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3307/guarderia_canina
spring.datasource.username=guarderia_user
<<<<<<< HEAD
spring.datasource.password=Elvivi920302425
=======
spring.datasource.password=**********

>>>>>>> 9e6b934e2f16c779c822eee498bf7233b6739223
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======



server.port=8081
>>>>>>> 9e6b934e2f16c779c822eee498bf7233b6739223
